### PR TITLE
Remove unnecessary jdt.ls config

### PR DESCRIPTION
**Pull request by fbricon**
jdt.ls project lead here. I noticed the jdt.ls config referenced missing bundles or unsupported configuration, so I just removed them.

### CODE REVIEW

**Comment by raxod502** [comment]
Thanks! I ran this locally and autocompletion still looks great, so, merging this!

image

While I've got you here, though, I was wondering, what would you recommend as the bare minimum way to set up a "project" that jdt.ls would be happy with, to clear the warning above? In Riju's environment, you only ever have one source file, but I assume Riju needs to automatically create a file in the directory to configure a "project" as well?

**Comment by maxandersen** [comment]
@raxod502 if you enabled jbang here it would generate the project info for you - just saying :)

**Comment by fbricon** [comment]
@raxod502 you need the source directory and the jdt.ls workspace (-data) to be different, the workspace shouldn't be nested under the sources, and vice-versa, and send a triggerFile parameter
So, if your source lives in $PWD, basically start the server with -data=/someting/different/jdt/specific.

then add :
- rootUri: file://$PWD
- triggerFiles: 
    - file://$PWD/Main.java

**Comment by raxod502** [comment]
Thank you! I changed the data directory in https://github.com/raxod502/riju/commit/efaaf73012eafdcce4b6a22dde5113c3ecf1a26d and it appears to be working great (at least locally)!

**Pull request merged**
